[
	{"text":"I hope this email finds you well.","label": "positive"},
	{"text":"I hope you had a good weekend.","label": "positive"},
	{"text":"I hope you had a great trip.","label": "positive"},
	{"text":"Hope you had a nice break.","label": "positive"},
	{"text":"I hope you are well.","label": "positive"},
	{"text":"I hope all is well.","label": "positive"},
	{"text":"It was a pleasure to meet you.","label": "positive"},
	{"text":"It was great to see you.","label": "positive"},
	{"text":"I am writing to you about our last meeting/your presentation yesterday/our next event.","label": "positive"},
	{"text":"I am writing to you with regards to/regarding/concerning/in connection with","label": "positive"},
	{"text":"I am writing to ask/enquire/let you know/confirm/check/invite you to/to update you on/ask for a favor","label": "positive"},
	{"text":"I am writing you to follow up on","label": "positive"},
	{"text":"I am contacting you to inform","label": "positive"},
	{"text":"This is just a quick reminder","label": "positive"},
	{"text":"As we discussed, I would like to send you","label": "positive"},
	{"text":"As we discussed, I would like to send you","label": "positive"},
	{"text":"Thank you for your email about","label": "positive"},
	{"text":"Thanks for your feedback","label": "positive"},
	{"text":"Thanks for your quick reply.","label": "positive"},
	{"text":"Thanks for getting back to me so quickly.","label": "positive"},
	{"text":"Thank you for reaching out.","label": "positive"},
	{"text":"Sorry for my late reply.","label": "positive"},
	{"text":"Sorry that it took me so long to get back to you.","label": "positive"},
	{"text":"I apologize for the late response.","label": "positive"},
	{"text":"Sorry it’s been so long since my last email.","label": "positive"},
	{"text":"Please accept our apologies for any inconvenience caused.","label": "positive"},
	{"text":"Could you please","label": "positive"},
	{"text":"Could you possibly tell me","label": "positive"},
	{"text":"Can you please fill out this form?","label": "positive"},
	{"text":"I'd really appreciate it if you could","label": "positive"},
	{"text":"I'd be very grateful if you could","label": "positive"},
	{"text":"I was wondering if you could","label": "positive"},
	{"text":"If possible, I'd like to know more","label": "positive"},
	{"text":"I didn't fully understand. Could you please explain that again?","label": "positive"},
	{"text":"I didn't quite get your point. Could you be more specific?","label": "positive"},
	{"text":"Could you repeat what you said?","label": "positive"},
	{"text":"Could you give us some more details?","label": "positive"},
	{"text":"When exactly are you expecting to have this feature?","label": "positive"},
	{"text":"If I understood you correctly.","label": "positive"},
	{"text":"What exactly do you mean?","label": "positive"},
	{"text":"In other words","label": "positive"},
	{"text":"Thanks for letting me know","label": "positive"},
	{"text":"Thank you for the heads up","label": "positive"},
	{"text":"Thank you for the notice.","label": "positive"},
	{"text":"Please note","label": "positive"},
	{"text":"Quick reminder","label": "positive"},
	{"text":"Thank you for sharing","label": "positive"},
	{"text":"Just a quick heads up","label": "positive"},
	{"text":"Thanks for keeping me in the loop","label": "positive"},
	{"text":"Please keep me informed","label": "positive"},
	{"text":"Please let me know if you are okay with this?,", "label": "positive"},
	{"text":"Please let me know what you think","label": "positive"},
	{"text":"What are your thoughts?","label": "positive"},
	{"text":"What do you think?","label": "positive"},
	{"text":"We just need the thumbs up.","label": "positive"},
	{"text":"Please guide me in this regard.","label": "positive"},
	{"text":"It has been approved.","label": "positive"},
	{"text":"I'd like to schedule a meeting","label": "positive"},
	{"text":"I am available","label": "positive"},
	{"text":"Can you make it","label": "positive"},
	{"text":"I'm afraid we need to reschedule","label": "positive"},
	{"text":"Looking forward to hearing from you soon","label": "positive"},
	{"text":"I look forward to hearing from you soon","label": "positive"},
	{"text":"Please let me know if this works","label": "positive"},
	{"text":"See you next week","label": "positive"},
	{"text":"Thanks","label": "positive"},
	{"text":"I'll get to it next week","label": "positive"},
	{"text":"Any feedack you can give me on this would be greatly appreciated","label": "positive"},
	{"text":"I hope you find this helpful","label": "positive"},
	{"text":"I hope it's clearer now","label": "positive"},
	{"text":"If we can be of any further assistance, please let us know","label": "positive"},
	{"text":"Let me know if you need any help.","label": "positive"},
	{"text":"For further details","label": "positive"},
	{"text":"If you have any more questions","label": "positive"},
	{"text":"please do not hesitate to contact me","label": "positive"},
	{"text":"please feel free to contact me","label": "positive"},
	{"text":"please let me know","label": "positive"},
	{"text":"drop me an email","label": "positive"},
	{"text":"Thank you for understanding","label": "positive"},
	{"text":"Thank you for your patience","label": "positive"},
	{"text":"Once again, please accept our apologies","label": "positive"},
	{"text":"I hope this is okay with you","label": "positive"},
	{"text":"I really hope we can find a solution soon","label": "positive"},
	{"text":"sorry I couldn't be of more help","label": "positive"},
	{"text":"best regards","label": "positive"},
	{"text":"all the best","label": "positive"},
	{"text":"cheers","label": "positive"},
	{"text":"dearly","label": "positive"},
	{"text":"have a great weekend","label": "positive"},
	{"text":"have a wonderful day","label": "positive"},
	{"text":"thanks for your time and consideration","label": "positive"},
	{"text":"that's great","label": "positive"},
	{"text":"our plan is on time","label": "positive"},
	{"text":"we appreciate the work you're doing","label": "positive"},
	{"text":"good job","label": "positive"},
	{"text":"my office is always open","label": "positive"},
	{"text":"keep up the good communication","label": "positive"},
	{"text":"continue the great work","label": "positive"},
	{"text":"I will keep in touch","label": "positive"},
	{"text":"Please remember to submit the data. Thanks.","label": "positive"},
	{"text":"you're too sensitive","label": "negative"},
	{"text":"why are you getting upset","label": "negative"},
	{"text":"no offense","label": "negative"},
	{"text":"whatever","label": "negative"},
	{"text":"if that's what you want to do","label": "negative"},
	{"text":"you should have known that","label": "negative"},
	{"text":"I was just kidding","label": "negative"},
	{"text":"why don't you","label": "negative"},
	{"text":"that was surprisingly good","label": "negative"},
	{"text":"I'm fine","label": "negative"},
	{"text":"do you know what I mean by that","label": "negative"},
	{"text":"I thought you knew","label": "negative"},
	{"text":"I wish that you would","label": "negative"},
	{"text":"I'm not mad","label": "negative"},
	{"text":"If only you were better at","label": "negative"},
	{"text":"you're so lucky","label": "negative"},
	{"text":"you just want everything to be perfect","label": "negative"},
	{"text":"I didn't know what you meant now","label": "negative"},
	{"text":"can't you read the email","label": "negative"},
	{"text":"are you paying attention","label": "negative"},
	{"text":"I'm not sure why you're having such hard time grasping this concept","label": "negative"},
	{"text":"please do not contact me further","label": "negative"},
	{"text":"I'm not sorry","label": "negative"},
	{"text":"Why weren't you replying to my email","label": "negative"},
	{"text":"Please keep up with the rest of the team","label": "negative"},
	{"text":"I can't answer any more questions. Try to answer them yourself.","label": "negative"},
	{"text":"Love you","label": "negative"},
	{"text":"what do you want","label": "negative"},
	{"text":"This isn't the place for you to share your ideas","label": "negative"},
	{"text":"Do this immediately","label": "negative"},
	{"text":"Send to me asap","label": "negative"},
	{"text":"Can't you see this is very important","label": "negative"},
	{"text":"I need you to do this","label": "negative"},
	{"text":"Hey it's nice to meet you","label": "negative"},
	{"text":"Hiii","label": "negative"},
	{"text":"Heyyy","label": "negative"},
	{"text":"Hellooo","label": "negative"},
	{"text":"Check the attachment","label": "negative"},
	{"text":"That's just how it is","label": "negative"},
	{"text":"I'm ot feeling well enough","label": "negative"},
	{"text":"I'm doing what you told me to do","label": "negative"},
	{"text":"It's none of your business","label": "negative"},
	{"text":"Before you say that, let me just say","label": "negative"},
	{"text":"That's not my job","label": "negative"},
	{"text":"Do you know what I mean","label": "negative"},
	{"text":"I'm running late","label": "negative"},
	{"text":"They'll never notice","label": "negative"},
	{"text":"That's nothing special","label": "negative"},
	{"text":"Let's go along to get along","label": "negative"},
	{"text":"Guess what I heard!","label": "negative"},
	{"text":"I already know that","label": "negative"},
	{"text":"No.","label": "negative"},
	{"text":"I'm totally screwed.","label": "negative"},
	{"text":"We're totally screwed.","label": "negative"},
	{"text":"Ha ha ha ha.. lol. lmao.","label": "negative"},
	{"text":"What's in it for me?","label": "negative"},
	{"text":"You're doing it wrong.","label": "negative"},
	{"text":"I couldn't care less.","label": "negative"},
	{"text":"I could care less.","label": "negative"},
	{"text":"Sorry (but not sorry).","label": "negative"},
	{"text":"You should be ashamed.","label": "negative"},
	{"text":"I forgot.","label": "negative"},
	{"text":"You guys","label": "negative"},
	{"text":"You're fired.","label": "negative"},
	{"text":"Are you mad at me?","label": "negative"},
	{"text":"Because I said so.","label": "negative"},
	{"text":"I don't know why you didn't see me.","label": "negative"},
	{"text":"I'm jealous of you.","label": "negative"},
	{"text":"That's not my fault!","label": "negative"},
	{"text":"!!","label": "negative"},
	{"text":"??","label": "negative"},
	{"text":"I do apologize","label": "negative"},
	{"text":"Let's just hope it goes away","label": "negative"},
	{"text":"I'm so busy!!!","label": "negative"},
	{"text":"It is what it is","label": "negative"},
	{"text":"I just can't empathize","label": "negative"},
	{"text":"it's your money","label": "negative"},
	{"text":"That'll never work","label": "negative"},
	{"text":"It's not fair!","label": "negative"},
	{"text":"I'm so hung-over","label": "negative"},
	{"text":"I don't know why they asked me","label": "negative"},
	{"text":"We've always done it this way.","label": "negative"},
	{"text":"That's my secret.","label": "negative"},
	{"text":"That's a secret.","label": "negative"},
	{"text":"I'll get to it later.","label": "negative"},
	{"text":"Not going to happen.","label": "negative"},
	{"text":"I'm not impressed","label": "negative"},
	{"text":"That's a stupid idea.","label": "negative"},
	{"text":"I could've done it better.","label": "negative"},
	{"text":"I'm super overwhelmed!","label": "negative"},
	{"text":"You must have read into things.","label": "negative"},
	{"text":"Whose fault is that?","label": "negative"},
	{"text":"That will never happen.","label": "negative"},
	{"text":"I could tell you but I'd have to kill you.","label": "negative"},
	{"text":"I'm kind of a big deal.","label": "negative"},
	{"text":"You wouldn't understand.","label": "negative"},
	{"text":"You still have questions?","label": "negative"},
	{"text":"Change this.","label": "negative"},
	{"text":"Fill it out quick.","label": "negative"},
	{"text":"See ya later alligator","label": "negative"},
	{"text":"Best,", "label": "neutral"},
	{"text":"Regards","label": "neutral"},
	{"text":"Will follow up","label": "neutral"},
	{"text":"Few questions:","label": "neutral"},
	{"text":"Thanks","label": "neutral"},
	{"text":"Excited to check it out","label": "neutral"},
	{"text":"To whom it may concern","label": "neutral"},
	{"text":"This is a reminder to everyone","label": "neutral"},
	{"text":"Make note of the date and time","label": "neutral"},
	{"text":"For anything urget, call","label": "neutral"},
	{"text":"I will be checking my email","label": "neutral"},
	{"text":"I'm writing to inform you","label": "neutral"},
	{"text":"I've attached the contract","label": "neutral"},
	{"text":"Please review","label": "neutral"},
	{"text":"I will be accepting feedback","label": "neutral"},
	{"text":"You should have recieved","label": "neutral"},
	{"text":"Let me know if you have any question","label": "neutral"},
	{"text":"Let me know what you think","label": "neutral"},
	{"text":"Let me know if you are okay with this?","label": "neutral"},
	{"text":"Thoughts?","label": "neutral"},
	{"text":"Any feedback?","label": "neutral"},
	{"text":"For further assistance, let us know","label": "neutral"},
	{"text":"Details available","label": "neutral"},
	{"text":"I would like to schedule a meeting to discuss the project further.","label": "neutral"},
	{"text":"What times are you available?","label": "neutral"},
	{"text":"Attached is the report you requested","label": "neutral"},
	{"text":"Thank you for your email. I will respond as soon as possible.","label": "neutral"},
	{"text":"I am writing to cofirm our previous agreement","label": "neutral"},
	{"text":"We are happy to announce the launch o our new product","label": "neutral"},
	{"text":"Please find enclosed the updated version of the contract.","label": "neutral"},
	{"text":"I look forward to hearing from you.","label": "neutral"},
	{"text":"I am available for a meeting at your convenience.","label": "neutral"},
	{"text":"I would like to propose a solution to the issue","label": "neutral"},
	{"text":"I am writing to follow up","label": "neutral"},
	{"text":"Please find attached the agenda for our upcoming meeting","label": "neutral"},
	{"text":"I am reaching out to you regarding the progress of the project","label": "neutral"},
	{"text":"I would like to request a change","label": "neutral"},
	{"text":"As per our agreement, I have attached the necessary documents","label": "neutral"},
	{"text":"I am sending this email to confirm the details of our meeting","label": "neutral"},
	{"text":"I have made the necessary changes","label": "neutral"},
	{"text":"I would like to schedule acall","label": "neutral"},
	{"text":"I would like to propose a new strategy","label": "neutral"},
	{"text":"I am writing to request your feedback","label": "neutral"},
	{"text":"Sending this email as a reminder","label": "neutral"},
	{"text":"The delievery of our project is currently on hold","label": "neutral"},
	{"text":"Please review and let me know your thoughts.","label": "neutral"},
	{"text":"I have scheduled at team meeting","label": "neutral"},
	{"text":"What are the next steps for the project","label": "neutral"},
	{"text":"The project is on schedule","label": "neutral"},
	{"text":"I would like to request an extension for the project","label": "neutral"},
	{"text":"I am writing to follow up on the status","label": "neutral"},
	{"text":"Discuss at your convenience","label": "neutral"},
	{"text":"I need your assistance","label": "neutral"},
	{"text":"Have we discussed implementation for this code","label": "neutral"},
	{"text":"Is it possible to reassign some tasks amongst the team","label": "neutral"},
	{"text":"I would like to propose a new approach","label": "neutral"},
	{"text":"The delivery is on time","label": "neutral"},
	{"text":"I am pleased to inform you","label": "neutral"},
	{"text":"I am writing to request additional resources","label": "neutral"},
	{"text":"Has the conference call been scheduled?","label": "neutral"},
	{"text":"I am open to feedback","label": "neutral"},
	{"text":"Good morning","label": "neutral"},
	{"text":"Good afternoon","label": "neutral"},
	{"text":"Hello","label": "neutral"},
	{"text":"Dear","label": "neutral"},
	{"text":"Hope this email finds you well","label": "neutral"},
	{"text":"Hope all is well","label": "neutral"},
	{"text":"Hope you are having a good day","label": "neutral"},
	{"text":"Stay safe","label": "neutral"},
	{"text":"Just wanted to touch base","label": "neutral"},
	{"text":"how is everything going on your end","label": "neutral"},
	{"text":"How is the project coming along?","label": "neutral"},
	{"text":"Just wanted to catch up","label": "neutral"},
	{"text":"Just wanted to say how much I appreciate your support","label": "neutral"},
	{"text":"is there anything I can assist with","label": "neutral"},
	{"text":"just wanted to remind you of our upcoming meeting","label": "neutral"},
	{"text":"hope you're finding time for learning and development","label": "neutral"},
	{"text":"Please review and let me know your thoughts","label": "neutral"},
	{"text":"Does the team have any input","label": "neutral"},
	{"text":"Talk soon","label": "neutral"},
	{"text":"All the best","label": "neutral"},
	{"text":"Keep well","label": "neutral"},
	{"text":"Keep safe","label": "neutral"},
	{"text":"Hope you're having a good week so far","label": "neutral"},
	{"text":"Can't wait to hear about your recent successes","label": "neutral"},
	{"text":"How's the new team placement working out?","label": "neutral"},
	{"text":"Let's strategize on how to move forward","label": "neutral"},
	{"text":"I would like to propse a plan of action","label": "neutral"},
	{"text":"I suggest that we take a proactive approach","label": "neutral"},
	{"text":"Let's encourage everyone to share their ideas and thoughts.","label": "neutral"},
	{"text":"I propse that we set clear and measurable targets","label": "neutral"},
	{"text":"I am committed to providing the support and resources","label": "neutral"},
	{"text":"I am confident that we can achieve success through collaboration","label": "neutral"},
	{"text":"I encourage all team members to take initiative","label": "neutral"},
	{"text":"I am committed to fostering a culture of continuos improvement","label": "neutral"},
	{"text":"realistic by ambitious goals","label": "neutral"},
	{"text":"establish clear protocols for communication and collaboration","label": "neutral"},
	{"text":"think outside the box and bring fresh perspectives","label": "neutral"},
	{"text":"establish a system for recognizing and rewarding excellence","label": "neutral"},
	{"text":"committed to fostering a positive and inclusive work environment","label": "neutral"}
]